### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by Source82** [pskiran1/TensorRT-support-for-Tensorflow-2-Object-Detection-Models#1]
Hi,

I was getting this error

**File "create_onnx.py", line 251, in update_preprocessor
    cast_node = [node for node in self.graph.nodes if node.op == "Tile" and cast_name in node.name][0]
IndexError: list index out of range**

So I commented this part of the code to get it work.

`## Get rid of the last node in second preprocessing branch with parent second TensorListStack node:
#cast_name = "StatefulPartitionedCall/"
#cast_node = [node for node in self.graph.nodes if node.op == "Tile" and cast_name in node.name][0]
#cast_node.outputs = []`

On a side note, please is there anyway of getting Jetson to register efficientNMS plugin?

Thanks

**Comment by Source82** [comment]
I realised I didnt install some of the packages well

**Comment by thiemoToadi** [comment]
@Source82 I am running into the same problem when trying to convert ssd_mobilenet_v2_320x320_coco from the tensorflow model zoo 2. What exactly did you do to fix this error?

**Comment by 4ff4n** [comment]
hello @Source82 , @thiemoToadi, I am facing the same issue, please assist me how did you guys manage to resolve it.
thanks

**Comment by r2ba7** [comment]
Same issue here

**Comment by franferraz98** [comment]
Hey @r2ba7 , @4ff4n , @thiemoToadi , @Source82 , @pskiran1 I'm facing the same issue. Did you manage to resolve this? How did you install the packages? I'm working on Jetson too.

**Comment by r2ba7** [comment]
@franferraz98 I actually don't know, I just updated the packages, changed environments and voila ..

**Comment by franferraz98** [comment]
@r2ba7 I've seen that this conversions are now [officially supported](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api), but I have the same issues than with this repo.

Could you please show me which packages you installed and how? Or maybe a `pip list`?

Thanks!
